<?php

namespace Admin\Controller;

class ProductController extends BaseController {

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function index(){
        return $this->display();
    }
}